version: '3.9'

services:
  db:
    image: postgres:14
    env_file: .env
    ports:
      - '5432:5432'  # Expose for local dev
    volumes:
      - group-project-data:/var/lib/postgresql/data 
      - ./SRC/init_data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      retries: 5

  web:
    image: node:lts
    user: 'node'
    working_dir: /repository
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    volumes:
      - ./:/repository
    command: 'npm run testandrun'  # Or 'npm run testandrun'

volumes:
  group-project-data: 